#ifndef CPP_EXAMPLE_IMAGING_OPS_REMAPTOLOGICALORDER_H
#define CPP_EXAMPLE_IMAGING_OPS_REMAPTOLOGICALORDER_H

namespace imaging {

class RemapToLogicalOrder {

};

}

#endif//CPP_EXAMPLE_IMAGING_OPS_REMAPTOLOGICALORDER_H
